CREATE TABLE flight_plans (
  flightRef varchar(10) NOT NULL,
  acid varchar(8) NOT NULL,
  departing_airport varchar(6) DEFAULT NULL,
  arrival_airport varchar(6) DEFAULT NULL,
  etd datetime DEFAULT NULL,
  eta datetime DEFAULT NULL,
  status enum('SCHEDULED','FLYING','ARRIVED','MAINTENANCE') DEFAULT NULL,
  fbo_id int DEFAULT NULL,
  PRIMARY KEY (flightRef),
  KEY parked_idx (arrival_airport)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE netjets_fleet (
  acid varchar(8) NOT NULL,
  plane_type varchar(6) DEFAULT NULL,
  flightRef varchar(10) NOT NULL,
  PRIMARY KEY (acid),
  UNIQUE KEY flightRef (flightRef)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE airport_parking (
  Airport_Code varchar(10) DEFAULT NULL,
  FBO_Name varchar(255) DEFAULT NULL,
  Total_Space int DEFAULT NULL,
  Area_ft2 decimal(15,2) DEFAULT NULL,
  iata_code varchar(10) DEFAULT NULL,
  id int NOT NULL AUTO_INCREMENT,
  Priority int NOT NULL,
  PRIMARY KEY (id),
  KEY idx_airport_fbo (Airport_Code,FBO_Name)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `airport_data` (
  `id` int DEFAULT NULL,
  `ident` varchar(10) NOT NULL,
  `type` varchar(50) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `latitude_deg` decimal(10,6) DEFAULT NULL,
  `longitude_deg` decimal(10,6) DEFAULT NULL,
  `elevation_ft` int DEFAULT NULL,
  `continent` varchar(5) DEFAULT NULL,
  `iso_country` varchar(5) DEFAULT NULL,
  `iso_region` varchar(10) DEFAULT NULL,
  `municipality` varchar(100) DEFAULT NULL,
  `scheduled_service` varchar(5) DEFAULT NULL,
  `gps_code` varchar(10) DEFAULT NULL,
  `iata_code` varchar(10) DEFAULT NULL,
  `local_code` varchar(10) DEFAULT NULL,
  `home_link` text,
  `wikipedia_link` text,
  `keywords` text,
  `capacity` int DEFAULT NULL,
  PRIMARY KEY (`ident`),
  KEY `idx_ident` (`ident`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO airport_parking VALUES
('KTEB','Atlantic Aviation',13,678710.89,'TEB',1,1),
('KTEB','Jet Aviation',10,996916.37,'TEB',2,2),
('KTEB','Signature Aviation East',9,254913.75,'TEB',3,3),
('KTEB','Signature Aviation South',23,620609.34,'TEB',4,4),
('KTEB','Signature Aviation West',10,283136.05,'TEB',5,5),
('KHPN','Million Air',22,574335.79,'HPN',6,1),
('KHPN','NetJets HPN Facility Bldg 6',1,30000.00,'HPN',7,2),
('KHPN','NetJets HPN Hangar 26',2,15000.00,'HPN',8,3),
('KHPN','Signature Aviation East',7,205216.15,'HPN',9,4),
('KHPN','Signature Aviation West',6,166488.70,'HPN',10,5),
('KPBI','Atlantic Aviation N236MJ',7,206450.47,'PBI',11,2),
('KPBI','Atlantic Aviation FKA Galaxy',7,206479.40,'PBI',12,1),
('KPBI','NetJets',16,429275.22,'PBI',13,3),
('KPBI','Signature',17,450511.60,'PBI',14,4),
('KLAS','Atlantic Aviation',11,307333.81,'LAS',15,1),
('KLAS','Caesars Hanger/Paradise Hangar',1,33697.04,'LAS',16,2),
('KLAS','Signature Flight Support',6,180215.56,'LAS',17,3),
('KBOS','Signature Aviation',5,145626.97,'BOS',18,1),
('KJAC','Jackson Hole Flight Services',4,105450.04,'JAC',19,1),
('KMDW','Atlantic',4,120637.16,'MDW',20,1),
('KMDW','Signature',3,100136.39,'MDW',21,2),
('KMDW','Signature Flight South (Hangar 23)',0,15896.35,'MDW',22,3),
('KMDW','Signature South',6,160546.32,'MDW',23,4),
('KSDL','Atlantic Aviation',4,114259.52,'SCF',24,1),
('KSDL','Hangar 1 (PVT/PNR)',2,75537.32,'SCF',25,2),
('KSDL','Jet Aviation',3,98873.84,'SCF',26,3),
('KSDL','NetJets',6,161172.18,'SCF',27,4),
('KSDL','Signature Flight Support',7,203346.99,'SCF',28,5),
('KDAL','Areo Star Aviation Main Hangar',1,30000.00,'DAL',29,1),
('KDAL','Bombardier Aerospace',4,104590.11,'DAL',30,2),
('KDAL','Signature Flight Support Terminal 1',6,169277.33,'DAL',31,3),
('KDAL','Signature Flight Support Terminal 2',6,167876.04,'DAL',32,4),
('KEGE','NetJets',9,244956.53,'EGE',33,1),
('KEGE','Signature',14,373383.53,'EGE',34,2),
('KMST','masters parking',8,117788.85,'MST',102,1);

INSERT INTO airport_data VALUES
(16091,'KABQ','large_airport','Albuquerque International Sunport',35.039976,-106.608925,5355,'NA','US','US-NM','Albuquerque','yes','KABQ','ABQ','ABQ','http://www.abqsunport.com/','https://en.wikipedia.org/wiki/Albuquerque_International_Sunport',NULL,NULL),
(3364,'KADW','large_airport','Joint Base Andrews',38.810799,-76.866997,280,'NA','US','US-MD','Camp Springs','no','KADW','ADW','ADW','http://www.jba.af.mil/','https://en.wikipedia.org/wiki/Joint_Base_Andrews','Andrews Air Force Base',NULL),
(3384,'KATL','large_airport','Hartsfield Jackson Atlanta International Airport',33.636700,-84.428101,1026,'NA','US','US-GA','Atlanta','yes','KATL','ATL','ATL','http://www.atlanta-airport.com/','https://en.wikipedia.org/wiki/Hartsfield-Jackson_Atlanta_International_Airport',NULL,NULL),
(3386,'KAUS','large_airport','Austin Bergstrom International Airport',30.197535,-97.662015,542,'NA','US','US-TX','Austin','yes','KAUS','AUS','AUS','http://www.ci.austin.tx.us/austinairport/','https://en.wikipedia.org/wiki/Austin-Bergstrom_International_Airport','BSM, KBSM, Bergstrom AFB',NULL),
(3396,'KBDL','large_airport','Bradley International Airport',41.938510,-72.688066,173,'NA','US','US-CT','Hartford','yes','KBDL','BDL','BDL','http://www.bradleyairport.com/','https://en.wikipedia.org/wiki/Bradley_International_Airport','HFD, Hartford',NULL),
(3420,'KBNA','large_airport','Nashville International Airport',36.124500,-86.678200,599,'NA','US','US-TN','Nashville','yes','KBNA','BNA','BNA','https://flynashville.com/','https://en.wikipedia.org/wiki/Nashville_International_Airport',NULL,NULL),
(3422,'KBOS','large_airport','Logan International Airport',42.361970,-71.007900,20,'NA','US','US-MA','Boston','yes','KBOS','BOS','BOS','http://www.massport.com/logan/','https://en.wikipedia.org/wiki/Logan_International_Airport','General Edward Lawrence Logan International Airport',NULL),
(3431,'KBUF','large_airport','Buffalo Niagara International Airport',42.940498,-78.732201,728,'NA','US','US-NY','Buffalo','yes','KBUF','BUF','BUF','https://www.buffaloairport.com/','https://en.wikipedia.org/wiki/Buffalo_Niagara_International_Airport',NULL,NULL),
(3435,'KBWI','large_airport','Baltimore/Washington International Thurgood Marshall Airport',39.175400,-76.668297,146,'NA','US','US-MD','Baltimore','yes','KBWI','BWI','BWI','https://www.bwiairport.com/','https://en.wikipedia.org/wiki/Baltimore%E2%80%93Washington_International_Airport','WAS, United States, Marshall',NULL),
(3454,'KCLE','large_airport','Cleveland Hopkins International Airport',41.411701,-81.849800,791,'NA','US','US-OH','Cleveland','yes','KCLE','CLE','CLE','http://www.clevelandairport.com/','https://en.wikipedia.org/wiki/Cleveland_Hopkins_International_Airport',NULL,NULL),
(3457,'KCLT','large_airport','Charlotte Douglas International Airport',35.214001,-80.943100,748,'NA','US','US-NC','Charlotte','yes','KCLT','CLT','CLT','http://www.charlotteairport.com/','https://en.wikipedia.org/wiki/Charlotte/Douglas_International_Airport',NULL,NULL),
(3458,'KCMH','large_airport','John Glenn Columbus International Airport',39.998001,-82.891899,815,'NA','US','US-OH','Columbus','yes','KCMH','CMH','CMH','https://flycolumbus.com/','https://en.wikipedia.org/wiki/Port_Columbus_International_Airport',NULL,NULL),
(3471,'KCVG','large_airport','Cincinnati Northern Kentucky International Airport',39.048801,-84.667801,896,'NA','US','US-KY','Cincinnati / Covington','yes','KCVG','CVG','CVG','https://www.cvgairport.com/','https://en.wikipedia.org/wiki/Cincinnati/Northern_Kentucky_International_Airport',NULL,NULL),
(3483,'KDCA','large_airport','Ronald Reagan Washington National Airport',38.852100,-77.037697,15,'NA','US','US-DC','Washington','yes','KDCA','DCA','DCA','http://www.flyreagan.com/dca/reagan-national-airport','https://en.wikipedia.org/wiki/Ronald_Reagan_Washington_National_Airport','WAS',NULL),
(3486,'KDEN','large_airport','Denver International Airport',39.861698,-104.672997,5431,'NA','US','US-CO','Denver','yes','KDEN','DEN','DEN','http://www.flydenver.com/','https://en.wikipedia.org/wiki/Denver_International_Airport','DVX, KVDX',NULL),
(3488,'KDFW','large_airport','Dallas Fort Worth International Airport',32.896801,-97.038002,607,'NA','US','US-TX','Dallas-Fort Worth','yes','KDFW','DFW','DFW','https://www.dfwairport.com/','https://en.wikipedia.org/wiki/Dallas/Fort_Worth_International_Airport','QDF',NULL),
(3497,'KDTW','large_airport','Detroit Metropolitan Wayne County Airport',42.213770,-83.353786,645,'NA','US','US-MI','Detroit','yes','KDTW','DTW','DTW','http://www.metroairport.com/','https://en.wikipedia.org/wiki/Detroit_Metropolitan_Wayne_County_Airport','DTT, Detroit Metro Airport',NULL),
(3521,'KEWR','large_airport','Newark Liberty International Airport',40.692501,-74.168701,18,'NA','US','US-NJ','Newark','yes','KEWR','EWR','EWR','http://www.panynj.gov/CommutingTravel/airports/html/newarkliberty.html','https://en.wikipedia.org/wiki/Newark_Liberty_International_Airport','Manhattan, New York City, NYC',NULL),
(3531,'KFLL','large_airport','Fort Lauderdale Hollywood International Airport',26.072599,-80.152702,9,'NA','US','US-FL','Fort Lauderdale','yes','KFLL','FLL','FLL','http://www.broward.org/airport','https://en.wikipedia.org/wiki/Fort_Lauderdale-Hollywood_International_Airport','MFW, South Florida',NULL),
(3602,'KIAD','large_airport','Washington Dulles International Airport',38.944500,-77.455803,312,'NA','US','US-VA','Dulles','yes','KIAD','IAD','IAD','http://www.mwaa.com/dulles/','https://en.wikipedia.org/wiki/Washington_Dulles_International_Airport','WAS',NULL),
(3604,'KIAH','large_airport','George Bush Intercontinental Houston Airport',29.984400,-95.341400,97,'NA','US','US-TX','Houston','yes','KIAH','IAH','IAH','http://www.fly2houston.com/iah','https://en.wikipedia.org/wiki/George_Bush_Intercontinental_Airport','QHO',NULL),
(3610,'KIND','large_airport','Indianapolis International Airport',39.717300,-86.294403,797,'NA','US','US-IN','Indianapolis','yes','KIND','IND','IND','http://www.indianapolisairport.com/','https://en.wikipedia.org/wiki/Indianapolis_International_Airport',NULL,NULL),
(3620,'KJAX','large_airport','Jacksonville International Airport',30.492469,-81.687813,30,'NA','US','US-FL','Jacksonville','yes','KJAX','JAX','JAX','https://www.flyjacksonville.com/','https://en.wikipedia.org/wiki/Jacksonville_International_Airport',NULL,NULL),
(3622,'KJFK','large_airport','John F Kennedy International Airport',40.639447,-73.779317,13,'NA','US','US-NY','New York','yes','KJFK','JFK','JFK','https://www.jfkairport.com/','https://en.wikipedia.org/wiki/John_F._Kennedy_International_Airport','Manhattan, New York City, NYC, Idlewild, IDL, KIDL',NULL),
(3631,'KLAS','large_airport','Harry Reid International Airport',36.083361,-115.151817,2181,'NA','US','US-NV','Las Vegas','yes','KLAS','LAS','LAS','https://www.harryreidairport.com/','https://en.wikipedia.org/wiki/Harry_Reid_International_Airport','McCarran International Airport',NULL),
(3632,'KLAX','large_airport','Los Angeles International Airport',33.942501,-118.407997,125,'NA','US','US-CA','Los Angeles','yes','KLAX','LAX','LAX','https://www.flylax.com/','https://en.wikipedia.org/wiki/Los_Angeles_International_Airport','Tom Bradley',NULL),
(3643,'KLGA','large_airport','LaGuardia Airport',40.777199,-73.872597,21,'NA','US','US-NY','New York','yes','KLGA','LGA','LGA','https://www.laguardiaairport.com/','https://en.wikipedia.org/wiki/LaGuardia_Airport','Manhattan, New York City, NYC, Glenn H. Curtiss Airport, North Beach Airport, La Guardia',NULL),
(3668,'KMCI','large_airport','Kansas City International Airport',39.297600,-94.713898,1026,'NA','US','US-MO','Kansas City','yes','KMCI','MCI','MCI','http://www.flykci.com/','https://en.wikipedia.org/wiki/Kansas_City_International_Airport',NULL,NULL),
(3670,'KMCO','large_airport','Orlando International Airport',28.429399,-81.308998,96,'NA','US','US-FL','Orlando','yes','KMCO','MCO','MCO','http://www.orlandoairports.net/','https://en.wikipedia.org/wiki/Orlando_International_Airport','Disney World,Epcot Center',NULL),
(3673,'KMDW','large_airport','Chicago Midway International Airport',41.785999,-87.752403,620,'NA','US','US-IL','Chicago','yes','KMDW','MDW','MDW','https://www.flychicago.com/midway/home/pages/default.aspx','https://en.wikipedia.org/wiki/Midway_International_Airport','CHI',NULL),
(3675,'KMEM','large_airport','Memphis International Airport',35.042400,-89.976700,341,'NA','US','US-TN','Memphis','yes','KMEM','MEM','MEM','https://flymemphis.com/','https://en.wikipedia.org/wiki/Memphis_International_Airport',NULL,NULL),
(3685,'KMIA','large_airport','Miami International Airport',25.793200,-80.290604,8,'NA','US','US-FL','Miami','yes','KMIA','MIA','MIA','http://www.miami-airport.com/','https://en.wikipedia.org/wiki/Miami_International_Airport','MFW, South Florida',NULL),
(3690,'KMKE','large_airport','General Mitchell International Airport',42.947201,-87.896599,723,'NA','US','US-WI','Milwaukee','yes','KMKE','MKE','MKE','https://www.mitchellairport.com/','https://en.wikipedia.org/wiki/General_Mitchell_International_Airport',NULL,NULL),
(3709,'KMSP','large_airport','Minneapolis-Saint Paul International Airport / Wold-Chamberlain Field',44.880081,-93.221741,841,'NA','US','US-MN','Minneapolis','yes','KMSP','MSP','MSP','http://www.mspairport.com/','https://en.wikipedia.org/wiki/Minneapolis-Saint_Paul_International_Airport',NULL,NULL),
(3711,'KMSY','large_airport','Louis Armstrong New Orleans International Airport',29.993401,-90.258003,4,'NA','US','US-LA','New Orleans','yes','KMSY','MSY','MSY','https://flymsy.com/','https://en.wikipedia.org/wiki/Louis_Armstrong_New_Orleans_International_Airport',NULL,NULL),
(3744,'KOAK','large_airport','San Francisco Bay Oakland International Airport',37.720085,-122.221184,9,'NA','US','US-CA','Oakland','yes','KOAK','OAK','OAK','http://www.oaklandairport.com/','https://en.wikipedia.org/wiki/Oakland_International_Airport','Metro Oakland International',NULL),
(3747,'KOKC','large_airport','Will Rogers World Airport',35.393388,-97.598248,1295,'NA','US','US-OK','Oklahoma City','yes','KOKC','OKC','OKC','https://flyokc.com/','https://en.wikipedia.org/wiki/Will_Rogers_World_Airport',NULL,NULL),
(3751,'KOMA','large_airport','Eppley Airfield',41.303200,-95.894096,984,'NA','US','US-NE','Omaha','yes','KOMA','OMA','OMA','https://www.flyoma.com','https://en.wikipedia.org/wiki/Eppley_Airfield',NULL,NULL),
(3752,'KONT','large_airport','Ontario International Airport',34.056000,-117.600998,944,'NA','US','US-CA','Ontario','yes','KONT','ONT','ONT','https://www.flyontario.com/','https://en.wikipedia.org/wiki/LA/Ontario_International_Airport',NULL,NULL),
(3754,'KORD','large_airport','Chicago OHare International Airport',41.978600,-87.904800,680,'NA','US','US-IL','Chicago','yes','KORD','ORD','ORD','https://www.flychicago.com/ohare/home/pages/default.aspx','https://en.wikipedia.org/wiki/OHare_International_Airport','CHI, Orchard Place',NULL),
(3755,'KORF','large_airport','Norfolk International Airport',36.895341,-76.201000,26,'NA','US','US-VA','Norfolk','yes','KORF','ORF','ORF','https://www.norfolkairport.com/','https://en.wikipedia.org/wiki/Norfolk_International_Airport',NULL,NULL),
(3766,'KPBI','large_airport','Palm Beach International Airport',26.683201,-80.095596,19,'NA','US','US-FL','West Palm Beach','yes','KPBI','PBI','PBI','https://www.pbia.org/','https://en.wikipedia.org/wiki/Palm_Beach_International_Airport','MFW, South Florida',NULL),
(3768,'KPDX','large_airport','Portland International Airport',45.588699,-122.598000,31,'NA','US','US-OR','Portland','yes','KPDX','PDX','PDX','https://www.flypdx.com/','https://en.wikipedia.org/wiki/Portland_International_Airport',NULL,NULL),
(3771,'KPHL','large_airport','Philadelphia International Airport',39.871899,-75.241096,36,'NA','US','US-PA','Philadelphia','yes','KPHL','PHL','PHL','http://www.phl.org/','https://en.wikipedia.org/wiki/Philadelphia_International_Airport',NULL,NULL),
(3772,'KPHX','large_airport','Phoenix Sky Harbor International Airport',33.435302,-112.005905,1135,'NA','US','US-AZ','Phoenix','yes','KPHX','PHX','PHX','http://phoenix.gov/skyharborairport/','https://en.wikipedia.org/wiki/Phoenix_Sky_Harbor_International_Airport',NULL,NULL),
(3778,'KPIT','large_airport','Pittsburgh International Airport',40.491501,-80.232903,1203,'NA','US','US-PA','Pittsburgh','yes','KPIT','PIT','PIT','https://flypittsburgh.com/','https://en.wikipedia.org/wiki/Pittsburgh_International_Airport',NULL,NULL),
(3795,'KPVD','large_airport','Theodore Francis Green State Airport',41.725038,-71.425668,55,'NA','US','US-RI','Warwick','yes','KPVD','PVD','PVD','https://flyri.com/','https://en.wikipedia.org/wiki/T._F._Green_Airport',NULL,NULL),
(3796,'KPWM','large_airport','Portland International Jetport',43.646198,-70.309303,76,'NA','US','US-ME','Portland','yes','KPWM','PWM','PWM','https://portlandjetport.org/','https://en.wikipedia.org/wiki/Portland_International_Jetport',NULL,NULL),
(3844,'KRDU','large_airport','Raleigh Durham International Airport',35.877602,-78.787498,435,'NA','US','US-NC','Raleigh/Durham','yes','KRDU','RDU','RDU','https://www.rdu.com/','https://en.wikipedia.org/wiki/Raleigh-Durham_International_Airport',NULL,NULL),
(3847,'KRIC','large_airport','Richmond International Airport',37.505199,-77.319702,167,'NA','US','US-VA','Richmond','yes','KRIC','RIC','RIC','https://flyrichmond.com/','https://en.wikipedia.org/wiki/Richmond_International_Airport',NULL,NULL),
(3853,'KRNO','large_airport','Reno Tahoe International Airport',39.499100,-119.767998,4415,'NA','US','US-NV','Reno','yes','KRNO','RNO','RNO','https://www.renoairport.com/','https://en.wikipedia.org/wiki/Reno-Tahoe_International_Airport',NULL,NULL),
(3858,'KRSW','large_airport','Southwest Florida International Airport',26.536200,-81.755203,30,'NA','US','US-FL','Fort Myers','yes','KRSW','RSW','RSW','http://www.flylcpa.com/','https://en.wikipedia.org/wiki/Southwest_Florida_International_Airport',NULL,NULL),
(3862,'KSAN','large_airport','San Diego International Airport',32.733601,-117.190002,17,'NA','US','US-CA','San Diego','yes','KSAN','SAN','SAN','http://www.san.org/','https://en.wikipedia.org/wiki/San_Diego_International_Airport','Lindbergh Field',NULL),
(3863,'KSAT','large_airport','San Antonio International Airport',29.533701,-98.469803,809,'NA','US','US-TX','San Antonio','yes','KSAT','SAT','SAT','https://www.sanantonio.gov/aviation','https://en.wikipedia.org/wiki/San_Antonio_International_Airport',NULL,NULL),
(3864,'KSAV','large_airport','Savannah Hilton Head International Airport',32.127602,-81.202103,50,'NA','US','US-GA','Savannah','yes','KSAV','SAV','SAV','https://savannahairport.com/','https://en.wikipedia.org/wiki/Savannah/Hilton_Head_International_Airport',NULL,NULL),
(3873,'KSDF','large_airport','Louisville Muhammad Ali International Airport',38.174400,-85.736000,501,'NA','US','US-KY','Louisville','yes','KSDF','SDF','SDF','http://www.flylouisville.com','https://en.wikipedia.org/wiki/Louisville_International_Airport','Louisville International, Standiford Field',NULL),
(3875,'KSEA','large_airport','Seattle-Tacoma International Airport',47.447943,-122.310276,433,'NA','US','US-WA','Seattle','yes','KSEA','SEA','SEA','https://www.portseattle.org/sea-tac','https://en.wikipedia.org/wiki/Seattle%E2%80%93Tacoma_International_Airport',NULL,NULL),
(3876,'KSFB','large_airport','Orlando Sanford International Airport',28.777599,-81.237503,55,'NA','US','US-FL','Orlando','yes','KSFB','SFB','SFB',NULL,'https://en.wikipedia.org/wiki/Orlando_Sanford_International_Airport',NULL,NULL),
(3878,'KSFO','large_airport','San Francisco International Airport',37.619806,-122.374821,13,'NA','US','US-CA','San Francisco','yes','KSFO','SFO','SFO','http://www.flysfo.com/','https://en.wikipedia.org/wiki/San_Francisco_International_Airport','QSF, QBA',NULL),
(3883,'KSJC','large_airport','Norman Y. Mineta San Jose International Airport',37.362452,-121.929188,62,'NA','US','US-CA','San Jose','yes','KSJC','SJC','SJC','https://www.flysanjose.com/','https://en.wikipedia.org/wiki/San_Jose_International_Airport',NULL,NULL),
(3887,'KSLC','large_airport','Salt Lake City International Airport',40.788860,-111.979866,4227,'NA','US','US-UT','Salt Lake City','yes','KSLC','SLC','SLC','https://slcairport.com/','https://en.wikipedia.org/wiki/Salt_Lake_City_International_Airport',NULL,NULL),
(3892,'KSMF','large_airport','Sacramento International Airport',38.695400,-121.591003,27,'NA','US','US-CA','Sacramento','yes','KSMF','SMF','SMF','https://sacramento.aero/smf','https://en.wikipedia.org/wiki/Sacramento_International_Airport',NULL,NULL),
(3894,'KSNA','large_airport','John Wayne Orange County International Airport',33.675701,-117.867996,56,'NA','US','US-CA','Santa Ana','yes','KSNA','SNA','SNA','http://www.ocair.com/','https://en.wikipedia.org/wiki/John_Wayne_Airport','Disney, Disneyland, Orange County',NULL),
(3899,'KSRQ','large_airport','Sarasota Bradenton International Airport',27.394631,-82.554359,30,'NA','US','US-FL','Sarasota/Bradenton','yes','KSRQ','SRQ','SRQ',NULL,'https://en.wikipedia.org/wiki/Sarasota-Bradenton_International_Airport',NULL,NULL),
(3905,'KSTL','large_airport','St. Louis Lambert International Airport',38.748697,-90.370003,618,'NA','US','US-MO','St Louis','yes','KSTL','STL','STL','https://www.flystl.com/','https://en.wikipedia.org/wiki/St._Louis_Lambert_International_Airport','Lambert St Louis',NULL),
(3913,'KSYR','large_airport','Syracuse Hancock International Airport',43.111198,-76.106300,421,'NA','US','US-NY','Syracuse','yes','KSYR','SYR','SYR','http://www.syrairport.org/','https://en.wikipedia.org/wiki/Syracuse_Hancock_International_Airport',NULL,NULL),
(3926,'KTPA','large_airport','Tampa International Airport',27.975500,-82.533203,26,'NA','US','US-FL','Tampa','yes','KTPA','TPA','TPA','https://www.tampaairport.com/','https://en.wikipedia.org/wiki/Tampa_International_Airport',NULL,NULL),
(3930,'KTUL','large_airport','Tulsa International Airport',36.198399,-95.888100,677,'NA','US','US-OK','Tulsa','yes','KTUL','TUL','TUL',NULL,'https://en.wikipedia.org/wiki/Tulsa_International_Airport',NULL,NULL),
(5388,'PANC','large_airport','Ted Stevens Anchorage International Airport',61.179004,-149.992561,152,'NA','US','US-AK','Anchorage','yes','PANC','ANC','ANC','https://dot.alaska.gov/anc/','https://en.wikipedia.org/wiki/Ted_Stevens_Anchorage_International_Airport',NULL,NULL),
(5453,'PHNL','large_airport','Daniel K Inouye International Airport',21.320620,-157.924228,13,'NA','US','US-HI','Honolulu, Oahu','yes','PHNL','HNL','HNL','http://airports.hawaii.gov/hnl/','https://en.wikipedia.org/wiki/Daniel_K._Inouye_International_Airport','Hickam Air Force Base, HIK, PHIK, KHNL, Honolulu International',NULL),
(5455,'PHOG','large_airport','Kahului International Airport',20.896263,-156.431837,54,'NA','US','US-HI','Kahului','yes','PHOG','OGG','OGG','https://airports.hawaii.gov/ogg/','https://en.wikipedia.org/wiki/Kahului_Airport',NULL,NULL);
